server:
  allowHeaders: Origin, Content-Type, Accept, X-Firebase-AppCheck,
  allowMethods: GET, POST, PUT, DELETE, OPTIONS,
  bodyLimit: 20 # bytes * 1024 * 1024
  host: 0.0.0.0
  shutdownTimeout: 30 # seconds

app:
  name: cnvrt
  jobFlushTimeout: 3600 # seconds
  supportedFileTypes: png, jpg, jpeg, webp, avif
  maxFileCount: 10

firebase:
  appCheckHeader: X-Firebase-AppCheck
