server:
  allowOrigins: http://localhost:3000,
  allowHeaders: Origin, Content-Type, Accept,
  allowMethods: GET, POST, PUT, DELETE, OPTIONS,
  bodyLimit: 20
  host: 0.0.0.0
app:
  name: imagewizard
  jobFlushTimeout: 10
